name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'VERSION'

env:
  ECR_REPOSITORY: allora-rag-model

jobs:
  fetch-version:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.fetch_version.outputs.VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Fetch version
        id: fetch_version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_OUTPUT

  build-and-push:
    name: Build and Push Docker Images to AWS ECR
    runs-on: ubuntu-latest
    needs: fetch-version
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GHActions-${{ github.run_id }}
          role-duration-seconds: 1200
          mask-aws-account-id: false

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push the Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ needs.fetch-version.outputs.VERSION }}
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max